cast building_id_govt to VARCHAR instead of DOUBLE. (#522)
Data fetch on dagster was failing with error:

sqlalchemy.exc.ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=INVALID_CAST_ARGUMENT, message="Cannot cast 'buildID319' to DOUBLE",`